### ISSUE TITLE
`growi_backup_1`の起動に失敗してしまう

### ISSUE THREAD

**Issue by emadurandal** [weseek/growi-docker-compose#22]
度々失礼します。

現在、今度は別案件で新規growiを立ち上げようとしているのですが、
examplesの

* backup-mongodb-data
* https-portal
* integrate-with-hackmd

の設定をマージしたものをdocker-compose.override.ymlとして立ち上げようとしております。

しかし、以下のログのように、`growi_backup_1`こと、mongodb-awesome-backupを使ったバックアップコンテナの起動が失敗してしまい、困っている状況です。

私のローカルのMac、AWS ECS、EC2上のubuntu 18.04の３環境でいずれも同じエラーが起きて止まっております。

```
ubuntu@wiki:~/growi$ docker-compose up -d
Creating network "growi_default" with the default driver
Pulling backup (weseek/mongodb-awesome-backup:latest)...
latest: Pulling from weseek/mongodb-awesome-backup
ff3a5c916c92: Already exists
a47330a39bf9: Pull complete
8a340d61bbcf: Pull complete
3adfab489142: Pull complete
45195ad27f97: Pull complete
Digest: sha256:e6e0ae86470aef79d029a539d0bcb049d804df27f4c3ff9f4fd9e7dea63ce806
Status: Downloaded newer image for weseek/mongodb-awesome-backup:latest
Creating growi_elasticsearch_1 ... 
Creating growi_plantuml_1      ... done
Creating growi_mariadb_1       ... 
Creating growi_mongo_1         ... done
Creating growi_backup_1        ... error

Creating growi_elasticsearch_1 ... done
:402: container init caused \"rootfs_linux.go:58: mounting \\\"/home/ubuntu/growi/crontab/root\\\" to rootfs \\\"/var/lib/docker/overlay2/520d94796d27bba44a6dCreating growi_mariadb_1       ... done
d/etc/crontabs/root\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
Creating growi_app_1           ... done
Creating growi_hackmd_1        ... done
Creating growi_https-portal_1  ... done

ERROR: for backup  Cannot start service backup: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"rootfs_linux.go:58: mounting \\\"/home/ubuntu/growi/crontab/root\\\" to rootfs \\\"/var/lib/docker/overlay2/520d94796d27bba44a6d6486fe33e2a896e2f9e48038303b7455b74e0e0f2998/merged\\\" at \\\"/var/lib/docker/overlay2/520d94796d27bba44a6d6486fe33e2a896e2f9e48038303b7455b74e0e0f2998/merged/etc/crontabs/root\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
ERROR: Encountered errors while bringing up the project.
```

（前回同様、不具合ではなく私の勘違いの可能性もあり、その辺不明な状況でのご連絡でIssue以外に最適な場所ありましたらご指示いただければと思います）

**Comment by utsushiiro** [comment]
##  エラーについて
エラーメッセージを整形するとだいたい以下のようになっています. 
```
ERROR: for backup  Cannot start service backup: OCI runtime create failed: container_linux.go:348: 
starting container process caused "process_linux.go:402: 
container init caused 
    "rootfs_linux.go:58:
    mounting "/home/ubuntu/growi/crontab/root" 
        to rootfs "/var/lib/docker/overlay2/520d9...2998/merged" 
        at "/var/lib/docker/overlay2/520d9...2998/merged/etc/crontabs/root" 
        caused "not a directory": unknown: Are you trying to mount a directory onto a file (or vice-versa)? 
        Check if the specified host path exists and is the expected type
```
docker-composeでのbackupの部分は以下の用になっていると思いますが,  
```
backup:
    image: weseek/mongodb-awesome-backup:0.2.0
    environment:
      - CRONMODE=true
      - CRON_EXPRESSION=0 4 * * *                               # change it
      # - AWS_ACCESS_KEY_ID=${Your IAM Access Key ID}           # change it
      # - AWS_SECRET_ACCESS_KEY=${Your IAM Secret Access Key}   # change it
      # - S3_TARGET_BUCKET_URL=s3://${Your Bucket Name}/        # change it
    links:
      - mongo:mongo
    volumes:
      - ./crontab/root:/var/spool/cron/crontabs/root
```

この部分でホスト側の`./crontab/root`ファイルをコンテナ内の`/var/spool/cron/crontabs/root`ファイルにマウントしています. このマウントによりコンテナ側のファイルをホスト側のファイルで上書きして, ホスト側からcronの設定を上書きできるようになっています.
```
    volumes:
      - ./crontab/root:/var/spool/cron/crontabs/root
```

上記のエラーメッセージを見る限りこの部分でエラーが起きており, おそらくホスト側の`./crontab/root`が存在しないことが原因ではないでしょうか？

[README.txtにあるように](https://github.com/weseek/growi-docker-compose/tree/master/examples/backup-mongodb-data#quick-start), 以下のコマンドを実行して`./crontab/root`を作成してみてください.

3. Copy config file of 'crond' to local repos root
    ```
    cp -rp examples/backup-mongodb-data/crontab .
    ```

## 相談場所について
> その辺不明な状況でのご連絡でIssue以外に最適な場所ありましたらご指示いただければと思います

Issueでももちろんかまいませんが(他の方が同様のケースに遭遇した際に検索がしやすくなりますので),
GROWI用のSlackがありそちらでも相談を受け付けております(こちらのほうが応答が早いかもしれません).

↓リンク
 <a href="https://growi-slackin.weseek.co.jp/"><img src="https://growi-slackin.weseek.co.jp/badge.svg"></a>
