### ISSUE TITLE
HackMDエディタで既存記述が表示できない・更新できない

### ISSUE THREAD

**Issue by busitd** [weseek/growi-docker-compose#24]
[質問]

host

| item    | version|
| ------- | ------ |
| GROWI   | 3.3.9  |
| node.js | 8.15.0 |
| npm     | 6.4.1  |
| yarn    | 1.12.3 |

 Client

| item    | version    |
| ------- | ---------- |
| OS      | Windows 10 |
| browser | Chrome     |

docker-composeで建てています。HackMDとの統合を試しているのですが、HackMD エディタを起動させたときに、既に存在する記述は表示されず、「←Start by entering a title here...」の新規作成のような画面になります。またHackMDエディタの画面で画面右下の[更新]ボタンを押しても、効いていないようです。

他の変更点としてはホストOS側ポートを3001でアクセスできるようにしています。
(3000に戻しても関係ありませんでした)

追記: ホストOS側にgrowiのボリュームをマウントしています.

```yaml
## docker-compose.yml
    ports:
      - 3001:3000
      
environment:
    - HACKMD_URI=http://localhost:3100
    - HACKMD_URI_FOR_SERVER=http://hackmd:3000


volumes:
   growi_data:
      driver_opts:
        type: none
        device: /home/vagrant/growi/_data/growi_data
        o: bind
   mongo_configdb:
      driver_opts:
        type: none
        device: /home/vagrant/growi/_data/mongo_configdb
        o: bind
   mongo_db:
      driver_opts:
        type: none
        device: /home/vagrant/growi/_data/mongo_db
        o: bind
   es_data:
      driver_opts:
        type: none
        device: /home/vagrant/growi/_data/es_data
        o: bind
   es_plugins:
      driver_opts:
        type: none
        device: /home/vagrant/growi/_data/es_plugins
        o: bind


## docker-compose.override.yml
environment:
    - GROWI_URI=http://localhost:3001
ports:
    - 3100:3000   # localhost only by default


```

growiページ(/test/hackmdtest)を開いたときのdocker-compose log:

```verilog
app_1            | [2019-02-26T02:58:45.754Z]  INFO: express/70 on e0a736df6076: ::ffff:10.0.2.2 <-- GET /test/hackmdtest HTTP/1.1 200 41859 - Chrome 72.0 Windows 10.0.0 42.380274 ms (req_id=087d9fd1-f7db-4421-a064-a2ef7ee05962)
app_1            | [2019-02-26T02:58:46.537Z]  INFO: express/70 on e0a736df6076: ::ffff:10.0.2.2 <-- GET /_api/bookmarks.get?page_id=5c749e9c08727b0047e88c6e HTTP/1.1 304 - http://localhost:3001/test/hackmdtest Chrome 72.0 Windows 10.0.0 6.222763 ms (req_id=74680f75-7a1a-45d2-8ce0-6972030e1c76)
app_1            | [2019-02-26T02:58:46.548Z]  INFO: express/70 on e0a736df6076: ::ffff:10.0.2.2 <-- GET /_api/comments.get?page_id=5c749e9c08727b0047e88c6e HTTP/1.1 304 - http://localhost:3001/test/hackmdtest Chrome 72.0 Windows 10.0.0 15.921974 ms (req_id=eb2b58fb-a16b-45c9-abf3-facb63a6f7c5)
app_1            | [2019-02-26T02:58:46.563Z]  INFO: express/70 on e0a736df6076: ::ffff:10.0.2.2 <-- GET /_api/attachments.list?page_id=5c749e9c08727b0047e88c6e HTTP/1.1 304 - http://localhost:3001/test/hackmdtest Chrome 72.0 Windows 10.0.0 4.583104 ms (req_id=9b5ea1e7-8a80-4171-8d34-b45cd4d46111)
app_1            | [2019-02-26T02:58:46.634Z]  INFO: express/70 on e0a736df6076: ::ffff:10.0.2.2 <-- POST /_api/pages.seen HTTP/1.1 200 51 http://localhost:3001/test/hackmdtest Chrome 72.0 Windows 10.0.0 8.587667 ms (req_id=414ceba1-5e12-4ee3-bfc2-1a3379e4e38c)
```

[Start to edit with HackMD]ボタンをクリックして、HackMDエディタを開いたときのdocker-compose log:

```verilog
hackmd_1         | 2019-02-26T03:01:22.327Z - info: ::ffff:172.20.0.6 - - [26/Feb/2019:03:01:22 +0000] "GET /Rk76xk0NS0ukLgJvJWNYGg HTTP/1.1" 200 44509 "-" "axios/0.18.0"
hackmd_1         |
app_1            | [2019-02-26T03:01:22.335Z]  INFO: express/70 on e0a736df6076: ::ffff:10.0.2.2 <-- POST /_api/hackmd.integrate HTTP/1.1 200 130 http://localhost:3001/test/hackmdtest Chrome 72.0 Windows 10.0.0 47.127005 ms (req_id=8d5450f9-5de0-4942-8d01-df0be44eb6ff)
hackmd_1         | 2019-02-26T03:01:22.696Z - info: ::ffff:10.0.2.2 - - [26/Feb/2019:03:01:22 +0000] "GET /Rk76xk0NS0ukLgJvJWNYGg?both HTTP/1.1" 304 - "http://localhost:3001/test/hackmdtest" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36"
hackmd_1         |
app_1            | [2019-02-26T03:01:22.744Z]  INFO: express/70 on e0a736df6076: ::ffff:10.0.2.2 <-- GET /_hackmd/load-styles HTTP/1.1 304 - - Chrome 72.0 Windows 10.0.0 3.511218 ms (req_id=67772c0a-1a88-4f9b-9fc9-1d48dee813eb)
hackmd_1         | 2019-02-26T03:01:22.856Z - info: ::ffff:10.0.2.2 - - [26/Feb/2019:03:01:22 +0000] "GET /config HTTP/1.1" 304 - "http://localhost:3100/Rk76xk0NS0ukLgJvJWNYGg?both" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36"
hackmd_1         |
app_1            | [2019-02-26T03:01:22.892Z]  INFO: express/70 on e0a736df6076: ::ffff:10.0.2.2 <-- GET /_hackmd/load-agent HTTP/1.1 304 - - Chrome 72.0 Windows 10.0.0 3.476705 ms (req_id=24484693-76d3-4cf7-97b2-22fb5f3af1dc)
hackmd_1         | 2019-02-26T03:01:24.134Z - info: ::ffff:10.0.2.2 - - [26/Feb/2019:03:01:24 +0000] "GET /me HTTP/1.1" 304 - "http://localhost:3100/Rk76xk0NS0ukLgJvJWNYGg?both" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36"
hackmd_1         |
```

期待する動作としては、HackMDエディタで既存の記述が表示できるようにすること、更新できるようにすることです。
